[versions]
android = "8.12.0"
kotlin = "2.2.10"

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
